### PR TITLE
Fix "init_install_output" error

### PR DESCRIPTION
**Pull request by mdionne**
This error:

  AttributeError: 'Buildroot' object has no attribute 'init_install_output'

can occur because init_install_output is initialized in the pkg_manager object but not in the buildroot object.

### CODE REVIEW

**Comment by mdionne** [comment]
This was introduced by commit e58f0f5c62fe35740cc3fc5fa8e7 which added an initialization in PackageManager but used it from Buildroot.

The other possible fix is to initialize it in __init__ for Buildroot.

**Comment by xsuchy** [comment]
Rebased and merged. Thank you.

**Comment by xsuchy** [comment]
Commit 85ab3ce
